-- Found ament_cmake: 0.9.7 (/home/arian/ros2_foxy/install/ament_cmake/share/ament_cmake/cmake)
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Found rosidl_default_generators: 1.0.0 (/home/arian/ros2_foxy/install/rosidl_default_generators/share/rosidl_default_generators/cmake)
-- Using all available rosidl_typesupport_c: rosidl_typesupport_introspection_c;rosidl_typesupport_fastrtps_c;rosidl_typesupport_connext_c
-- Found rosidl_adapter: 1.1.0 (/home/arian/ros2_foxy/install/rosidl_adapter/share/rosidl_adapter/cmake)
-- Found FastRTPS: /home/arian/ros2_foxy/install/fastrtps/include  
-- Found RTI Connext: /home/arian/rti_connext_dds-5.3.1
-- Using all available rosidl_typesupport_cpp: rosidl_typesupport_introspection_cpp;rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_connext_cpp
-- Found PythonInterp: /usr/bin/python3 (found version "3.8.5") 
CMake Error at /home/arian/ros2_foxy/install/rosidl_adapter/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:60 (message):
  execute_process(/usr/bin/python3 -m rosidl_adapter --package-name
  tutorial_interfaces --arguments-file
  /home/arian/Desktop/someCandCppExamples/ROS2/dev_ws/build/tutorial_interfaces/rosidl_adapter__arguments__tutorial_interfaces.json
  --output-dir
  /home/arian/Desktop/someCandCppExamples/ROS2/dev_ws/build/tutorial_interfaces/rosidl_adapter/tutorial_interfaces
  --output-file
  /home/arian/Desktop/someCandCppExamples/ROS2/dev_ws/build/tutorial_interfaces/rosidl_adapter/tutorial_interfaces.idls)
  returned error code 1:

  Error processing 'int64 num[]' of 'tutorial_interfaces/Num': ''num[]' is an
  invalid field name.  It should have the pattern
  '^(?!.*__)(?!.*_$)[a-z][a-z0-9_]*$''

  Traceback (most recent call last):

    File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/home/arian/ros2_foxy/install/rosidl_adapter/lib/python3.8/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
    File "/home/arian/ros2_foxy/install/rosidl_adapter/lib/python3.8/site-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
    File "/home/arian/ros2_foxy/install/rosidl_adapter/lib/python3.8/site-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
      return convert_msg_to_idl(
    File "/home/arian/ros2_foxy/install/rosidl_adapter/lib/python3.8/site-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
      msg = parse_message_string(package_name, input_file.stem, content)
    File "/home/arian/ros2_foxy/install/rosidl_adapter/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 512, in parse_message_string
      fields.append(Field(
    File "/home/arian/ros2_foxy/install/rosidl_adapter/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 353, in __init__
      raise NameError(

  NameError: 'num[]' is an invalid field name.  It should have the pattern
  '^(?!.*__)(?!.*_$)[a-z][a-z0-9_]*$'

Call Stack (most recent call first):
  /home/arian/ros2_foxy/install/rosidl_cmake/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
  CMakeLists.txt:26 (rosidl_generate_interfaces)


-- Configuring incomplete, errors occurred!
See also "/home/arian/Desktop/someCandCppExamples/ROS2/dev_ws/build/tutorial_interfaces/CMakeFiles/CMakeOutput.log".
make: *** [Makefile:222: cmake_check_build_system] Error 1
